2012-11-05 03:34:18,077 INFO : Logging in as qbfb.joseph@gmail.com
2012-11-05 03:34:19,253 INFO : Got the email today from QuickBooks.
2012-11-05 03:34:19,253 INFO : Will fetch the exported data.
2012-11-05 03:34:19,253 ERROR : Traceback (most recent call last):
  File "./qb_check_email.py", line 47, in <module>
    msg = email.message_from_string(response_part[1])
IndexError: string index out of range

2012-11-05 03:34:19,393 INFO : Signing out...
2012-11-05 03:34:19,529 INFO : ('BYE', ['LOGOUT Requested'])
2012-11-05 04:01:01,530 INFO : Proceeding in requesting for data export.
2012-11-05 04:01:01,531 INFO : Opening firefox...
2012-11-05 06:01:01,803 INFO : Proceeding in requesting for data export.
2012-11-05 06:01:01,803 INFO : Opening firefox...
2012-11-07 04:50:42,970 INFO : Proceeding in requesting for data export.
2012-11-07 04:50:42,971 INFO : Opening firefox...
2012-11-07 04:51:01,459 INFO : Proceeding in requesting for data export.
2012-11-07 04:51:01,460 INFO : Opening firefox...
2012-11-07 04:51:12,091 INFO : Logging in as qbfb.joseph
2012-11-07 04:51:16,350 INFO : Requesting data...
2012-11-07 04:52:27,221 INFO : Request for today has been recorded.
2012-11-07 04:52:27,221 INFO : REQUEST FOR TODAY, 2012-11-06, WRITTEN TO LOG FILE!
2012-11-07 04:52:59,787 INFO : Signing out
2012-11-07 04:55:55,424 INFO : Logging in as qbfb.joseph@gmail.com
2012-11-07 04:55:56,435 INFO : Got the email today from QuickBooks.
2012-11-07 04:55:56,435 INFO : Will fetch the exported data.
2012-11-07 04:55:56,436 ERROR : Traceback (most recent call last):
  File "./qb_check_email.py", line 57, in <module>
    mail_timestamp = msg['date'][5:23+len(str(int(pdt_curr_datetime.strftime('%d'))))]
TypeError: 'NoneType' object is not subscriptable

2012-11-07 04:55:56,580 INFO : Signing out...
2012-11-07 04:55:56,717 INFO : ('BYE', ['LOGOUT Requested'])
2012-11-07 04:57:48,054 INFO : Getting configurations...
2012-11-07 04:58:08,581 INFO : Logging in as qbfb.joseph
2012-11-07 04:58:38,611 INFO : Extracting data...
2012-11-07 04:59:09,878 INFO : Writing data to export_company_20121106_2159.qbxml
2012-11-07 04:59:09,879 INFO : Dump written to export_company_20121106_2159.qbxml
2012-11-07 04:59:48,677 INFO : running this command - python /home/ubuntu/qboe/test_repo_2/quickbooks_export_data/../utils/sendmail.py --cfg /home/ubuntu/qboe/test_repo_2/quickbooks_export_data/qb_export_data.cfg --subject "QuickBooks Data Dump has been extracted." --message "Please check file export_company_20121106_2159.qbxml for its contents."
2012-11-07 04:59:48,678 INFO : Signing out...
2012-11-07 04:59:49,424 INFO : Exporting finished successfully.
2012-11-07 04:59:49,425 INFO : Exiting...
2012-11-13 03:37:06,828 INFO : Proceeding in requesting for data export.
2012-11-13 03:37:06,829 INFO : Opening firefox...
2012-11-13 03:37:18,879 INFO : Logging in as qbfb.joseph
2012-11-13 03:37:28,898 INFO : Requesting data...
2012-11-13 03:38:39,870 INFO : Request for today has been recorded.
2012-11-13 03:38:39,870 INFO : REQUEST FOR TODAY, 2012-11-12, WRITTEN TO LOG FILE!
2012-11-13 03:44:05,010 INFO : Request has been made already. Please wait for the email to be delivered.
2012-11-13 03:44:05,398 INFO : Logging in as qbfb.joseph@gmail.com
2012-11-13 03:44:06,569 INFO : Got the email today from QuickBooks.
2012-11-13 03:44:06,569 INFO : Will fetch the exported data.
2012-11-13 03:44:06,570 ERROR : Traceback (most recent call last):
  File "qb_check_email.py", line 57, in <module>
    mail_timestamp = msg['date'][5:23+len(str(int(pdt_curr_datetime.strftime('%d'))))]
TypeError: 'NoneType' object is not subscriptable

2012-11-13 03:44:06,960 INFO : Signing out...
2012-11-13 03:44:07,182 INFO : ('BYE', ['LOGOUT Requested'])
2012-11-13 03:44:07,843 INFO : Getting configurations...
2012-11-13 03:44:38,322 INFO : Logging in as qbfb.joseph
2012-11-13 03:45:08,349 INFO : Extracting data...
2012-11-13 03:45:39,408 INFO : Writing data to export_company_20121112_2045.qbxml
2012-11-13 03:45:39,408 INFO : Dump written to export_company_20121112_2045.qbxml
2012-11-13 03:46:19,946 INFO : running this command - python /home/ubuntu/qboe/test_repo_2/quickbooks_export_data/../utils/sendmail.py --cfg /home/ubuntu/qboe/test_repo_2/quickbooks_export_data/qb_export_data.cfg --subject "QuickBooks Data Dump has been extracted." --message "Please check file export_company_20121112_2045.qbxml for its contents."
2012-11-13 03:46:19,947 INFO : Signing out...
2012-11-13 03:46:20,697 INFO : Exporting finished successfully.
2012-11-13 03:46:20,697 INFO : Exiting...
2013-01-16 15:35:39,873 INFO : Getting configurations...
2013-03-14 09:07:21,798 INFO : Proceeding in requesting for data export.
2013-03-14 09:07:21,799 INFO : Opening firefox...
2013-03-14 09:07:23,452 ERROR : Traceback (most recent call last):
  File "qb_export_data_request.py", line 47, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 51, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 44, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 81, in _wait_until_connectable
    self._get_firefox_output())
WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: Error: no display specified\n' 

2013-03-14 09:14:40,803 INFO : Proceeding in requesting for data export.
2013-03-14 09:14:40,804 INFO : Opening firefox...
2013-03-14 09:14:56,594 INFO : Logging in as spof.qb.test
2013-03-14 09:14:57,751 INFO : Requesting data...
2013-03-14 09:16:08,902 INFO : Request for today has been recorded.
2013-03-14 09:16:08,902 INFO : REQUEST FOR TODAY, 2013-03-14, WRITTEN TO LOG FILE!
2013-03-14 09:16:41,449 INFO : Signing out
2013-03-14 09:16:41,527 ERROR : Traceback (most recent call last):
  File "qb_export_data_request.py", line 84, in <module>
    driver.find_element_by_link_text('Sign Out').click()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 237, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 671, in find_element
    {'using': by, 'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 156, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 147, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchElementException: Message: u'Unable to locate element: {"method":"link text","selector":"Sign Out"}' 

2013-03-14 09:19:39,000 INFO : Request has been made already. Please wait for the email to be delivered.
